config/routes.rb
Rails.application.routes.draw do
  resources :ninety_ten_bookings
  resources :ninety_ten_bookings
  resources :bookings
  resources :articles

  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  

end

app/models/ninety_ten_booking.rb
class NinetyTenBooking < ActiveRecord::Base
    validates :date__c, presence: true
    validates :time__c, presence: true
    validates :firstname__c, presence: true
    validates :lastname__c, presence: true
    validates :phonenumber__c, presence: true
    validates :guests__c, presence: true
    validates :username__c, presence: true
  self.table_name = 'ninetytenbookings.booking__c'
end

app/controllers/ninety_ten_bookings_controller.rb
class NinetyTenBookingsController < ApplicationController
  before_action :set_ninety_ten_booking, only: [:show, :edit, :update, :destroy]

  # GET /ninety_ten_bookings
  # GET /ninety_ten_bookings.json
  def index
    @ninety_ten_bookings = NinetyTenBooking.all
  end

  # GET /ninety_ten_bookings/1
  # GET /ninety_ten_bookings/1.json
  def show
  end

  # GET /ninety_ten_bookings/new
  def new
    @ninety_ten_booking = NinetyTenBooking.new
  end

  # GET /ninety_ten_bookings/1/edit
  def edit
  end

  # POST /ninety_ten_bookings
  # POST /ninety_ten_bookings.json
  def create
    @ninety_ten_booking = NinetyTenBooking.new(ninety_ten_booking_params)

    respond_to do |format|
      if @ninety_ten_booking.save
        format.html { redirect_to @ninety_ten_booking, notice: 'Ninety ten booking was successfully created.' }
        format.json { render :show, status: :created, location: @ninety_ten_booking }
      else
        format.html { render :new }
        format.json { render json: @ninety_ten_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ninety_ten_bookings/1
  # PATCH/PUT /ninety_ten_bookings/1.json
  def update
    respond_to do |format|
      if @ninety_ten_booking.update(ninety_ten_booking_params)
        format.html { redirect_to @ninety_ten_booking, notice: 'Ninety ten booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @ninety_ten_booking }
      else
        format.html { render :edit }
        format.json { render json: @ninety_ten_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninety_ten_bookings/1
  # DELETE /ninety_ten_bookings/1.json
  def destroy
    @ninety_ten_booking.destroy
    respond_to do |format|
      format.html { redirect_to ninety_ten_bookings_url, notice: 'Ninety ten booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ninety_ten_booking
      @ninety_ten_booking = NinetyTenBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ninety_ten_booking_params
      params.require(:ninety_ten_booking).permit(:date__c, :time__c, :firstname__c, :lastname__c, :phonenumber__c, :guests__c, :comments__c, :status__c, :username__c)
    end
end

app/helpers/ninety_ten_bookings_helper.rb
module NinetyTenBookingsHelper
end

app/views/ninety_ten_bookings/_form.html.1.erb
<%= render 'shared/errors', obj:@ninety_ten_booking %>

<div class='row'>
    <div class='col-xs-12'>    
        <%= form_for(@ninety_ten_booking, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :date__c %>
            </div>
            <div class="col-sm-8">
                <%= f.date_select :date__c, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :time__c %>
            </div>
            <div class="col-sm-8">
                <%= f.time_select :time__c, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :firstname__c %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :firstname__c, class: "form-control", placeholder: "Enter the First Name of the Guest", autofocus: true%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :lastname__c %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :lastname__c, class: "form-control", placeholder: "Enter the Last Name of the Guest"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :phonenumber__c %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :phonenumber__c, class: "form-control", placeholder: "Enter the phone number of the Guest"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :guests__c %>
            </div>
            <div class="col-sm-8">
                <%= f.number_field :noOfGuests__c, class: "form-control", placeholder: "2"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :status__c %>
            </div>
            <div class="col-sm-8" >
                <div class="form-control" >
                    <%= f.select :status__c, ['Confirmed','Cancelled'] %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username__c %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username__c, class: "form-control", placeholder: "pereira.andrew", autofocus: true%>
            </div>
        </div>        
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :comments__c %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :comments__c, class: "form-control", rows: "10", placeholder: "Enter any special requests or notes for the booking"%>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-lg'%>
            </div>
        </div>        
    </div>
</div>

<% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel and return to bookings listing", ninety_ten_bookings_path %> ]
</div>

app/views/ninety_ten_bookings/_form.html.erb
<%= render 'shared/errors', obj:@ninety_ten_booking %>

<div class='row'>
    <div class='col-xs-12'>    
        <%= form_for(@ninety_ten_booking, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Date
            </div>
            <div class="col-sm-8">
                <%= f.date_select :date__c, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Time
            </div>
            <div class="col-sm-8">
                <%= f.time_select :time__c, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                First Name
            </div>
            <div class="col-sm-8">
                <%= f.text_field :firstname__c, class: "form-control", placeholder: "Enter the First Name of the Guest", autofocus: true%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Last Name
            </div>
            <div class="col-sm-8">
                <%= f.text_field :lastname__c, class: "form-control", placeholder: "Enter the Last Name of the Guest"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Phone Number
            </div>
            <div class="col-sm-8">
                <%= f.text_field :phonenumber__c, class: "form-control", placeholder: "Enter the phone number of the Guest"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Items
            </div>
            <div class="col-sm-8">
                <%= f.number_field :guests__c, class: "form-control", placeholder: "2"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Status
            </div>
            <div class="col-sm-8" >
                <div class="form-control" >
                    <%= f.select :status__c, ['Confirmed','Cancelled'] %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                Username:
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username__c, class: "form-control", placeholder: "pereira.andrew", autofocus: true%>
            </div>
        </div>        
        <div class="form-group">
            <div class="control-label col-sm-2">
                Comments
            </div>
            <div class="col-sm-8">
                <%= f.text_area :comments__c, class: "form-control", rows: "10", placeholder: "Enter any special requests or notes for the booking"%>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-lg'%>
            </div>
        </div>        
    </div>
</div>

<% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel and return to bookings listing", ninety_ten_bookings_path %> ]
</div>

app/views/ninety_ten_bookings/_form.html_backup.erb
<%= render 'shared/errors', obj:@ninety_ten_booking %>

<div class='row'>
    <div class='col-xs-12'>    
        <%= form_for(@ninety_ten_booking, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :date %>
            </div>
            <div class="col-sm-8">
                <%= f.date_select :date, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :time %>
            </div>
            <div class="col-sm-8">
                <%= f.time_select :time, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :firstName %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :firstName, class: "form-control", placeholder: "Enter the First Name of the Guest", autofocus: true%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :lastName %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :lastName, class: "form-control", placeholder: "Enter the Last Name of the Guest"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :phoneNumber %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :phoneNumber, class: "form-control", placeholder: "Enter the phone number of the Guest"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :noOfGuests %>
            </div>
            <div class="col-sm-8">
                <%= f.number_field :noOfGuests, class: "form-control", placeholder: "2"%>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :status %>
            </div>
            <div class="col-sm-8" >
                <div class="form-control" >
                    <%= f.select :status, ['Confirmed','Cancelled'] %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "pereira.andrew", autofocus: true%>
            </div>
        </div>        
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :comments %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :comments, class: "form-control", rows: "10", placeholder: "Enter any special requests or notes for the booking"%>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-lg'%>
            </div>
        </div>        
    </div>
</div>

<% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel and return to bookings listing", ninety_ten_bookings_path %> ]
</div>

app/views/ninety_ten_bookings/edit.html.1.erb
<h1 align="center">Edit the Booking</h1>

<%= render 'form' %>

app/views/ninety_ten_bookings/edit.html.erb
<h1 align="center">Edit the Booking</h1>

<%= render 'form' %>

app/views/ninety_ten_bookings/index.html.1.erb
<h1 align="center">Listing all Bookings</h1>

<div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <%= link_to "Create a new Booking", new_ninety_ten_booking_path, class: "btn btn-xs btn-success" %>
        </div>
</div>

<% @ninety_ten_bookings.each do |ninety_ten_booking| %>
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="ninety_ten_booking-title">
               [ <%= link_to ninety_ten_booking.firstName, ninety_ten_booking_path(ninety_ten_booking) %> <%= link_to ninety_ten_booking.lastName, ninety_ten_booking_path(ninety_ten_booking) %> ]
            </div>
            <div class="ninety_ten_booking-body">
                Date: <%= ninety_ten_booking.date  %><br>
                Time: <%= ninety_ten_booking.time.strftime("%H:%M")  %><br>
                Guests:<%= ninety_ten_booking.noOfGuests  %><br>
                Status: <%= ninety_ten_booking.status  %>
            </div>
            <div class="ninety_ten_booking-actions">
                <%= link_to "Edit this ninety_ten_booking", edit_ninety_ten_booking_path(ninety_ten_booking), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete this ninety_ten_booking", ninety_ten_booking_path(ninety_ten_booking), method: :delete,
                                                                                    data: {confirm: "Are you sure you want to delete this Booking?"}, 
                                                                                    class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
<% end %>
    

app/views/ninety_ten_bookings/index.html.erb
<h1 align="center">Bookings</h1>

<div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <%= link_to "Create a new Booking", new_ninety_ten_booking_path, class: "btn btn-xs btn-success" %>
        </div>
</div>

<div class="col-xs-8 col-xs-offset-2">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Date</th>
      <th scope="col">Items</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    
<% @ninety_ten_bookings.each do |ninety_ten_booking| %>
    <tr>
      <th scope="row"></th>
      <td><%= link_to ninety_ten_booking.id, ninety_ten_booking_path(ninety_ten_booking) %></td>
      <td><%= ninety_ten_booking.firstname__c %></td>
      <td><%= ninety_ten_booking.lastname__c %></td>      
      <td><%= ninety_ten_booking.date__c  %></td>
      <td><%= ninety_ten_booking.guests__c  %></td>
      <td><%= ninety_ten_booking.phonenumber__c  %></td>
      <td><%= ninety_ten_booking.status__c  %></td>
      <td><%= link_to "View", ninety_ten_booking_path(ninety_ten_booking), class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to "Edit", edit_ninety_ten_booking_path(ninety_ten_booking), class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to "Delete", ninety_ten_booking_path(ninety_ten_booking), method: :delete,
                                                                                    data: {confirm: "Are you sure you want to delete this Booking?"}, 
                                                                                    class: "btn btn-xs btn-danger" %></td>
    </tr>
<% end %>

  </tbody>
</table>
</div>

app/views/ninety_ten_bookings/new.html.1.erb
<h1 align="center">Create a new Booking</h1>

<%= render 'form' %>

app/views/ninety_ten_bookings/new.html.erb
<h1 align="center">Create a new Booking</h1>

<%= render 'form' %>

app/views/ninety_ten_bookings/show.html.1.erb
<h2 align="center">Booking for: <%= @ninety_ten_booking.firstName %> <%= @ninety_ten_booking.lastName %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Booking Details</strong></h4>
    <hr>Date: <%= @ninety_ten_booking.date %>
    <hr>Time: <%= @ninety_ten_booking.time.strftime("%H:%M") %>
    <hr>First Name: <%= @ninety_ten_booking.firstName %>
    <hr>Last Name: <%= @ninety_ten_booking.lastName %>
    <hr>Phone Number: <%= @ninety_ten_booking.phoneNumber %>
    <hr>Number of Guests: <%= @ninety_ten_booking.noOfGuests %>
    <hr>Status: <%= @ninety_ten_booking.status %>
    <hr>Username: <%= @ninety_ten_booking.username %>
    <hr>Comments: <%= simple_format(@ninety_ten_booking.comments) %>
    <hr>
    <div class="ninety_ten_booking-actions">
        <%= link_to "Edit this ninety_ten_booking", edit_ninety_ten_booking_path(@ninety_ten_booking), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this ninety_ten_booking", ninety_ten_booking_path(@ninety_ten_booking), method: :delete,
                                                                            data: {confirm: "Are you sure you want to delete this booking?"}, 
                                                                            class: "btn btn-xs btn-danger" %>
        <%= link_to "View All ninety_ten_bookings", ninety_ten_bookings_path, class: "btn btn-xs btn-success" %>                                                                            
    </div>
</div>


    

app/views/ninety_ten_bookings/show.html.erb
<h2 align="center">Booking for: <%= @ninety_ten_booking.firstname__c %> <%= @ninety_ten_booking.lastname__c %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Booking Details</strong></h4>
    <hr>Id: <%= @ninety_ten_booking.id %>
    <hr>Date: <%= @ninety_ten_booking.date__c %>
    <hr>Time: <%= @ninety_ten_booking.time__c.strftime("%H:%M") %>
    <hr>First Name: <%= @ninety_ten_booking.firstname__c %>
    <hr>Last Name: <%= @ninety_ten_booking.lastname__c %>
    <hr>Phone Number: <%= @ninety_ten_booking.phonenumber__c %>
    <hr>Number of Items: <%= @ninety_ten_booking.guests__c %>
    <hr>Status: <%= @ninety_ten_booking.status__c %>
    <hr>Username: <%= @ninety_ten_booking.username__c %>
    <hr>Comments: <%= simple_format(@ninety_ten_booking.comments__c) %>
    <hr>
    <div class="ninety_ten_booking-actions">
        <%= link_to "View All", ninety_ten_bookings_path, class: "btn btn-xs btn-success" %>                                                                            
        <%= link_to "Edit", edit_ninety_ten_booking_path(@ninety_ten_booking), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", ninety_ten_booking_path(@ninety_ten_booking), method: :delete,
                                                                            data: {confirm: "Are you sure you want to delete this booking?"}, 
                                                                            class: "btn btn-xs btn-danger" %>
    </div>
</div>


    