config/routes.rb
Rails.application.routes.draw do
  resources :ninety_ten_bookings
  resources :ninety_ten_bookings
  resources :bookings
  resources :articles

  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true
    validates :description, presence: true
    
end 

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   before_action :set_param, only: [:edit, :update, :show, :destroy]
   
   def index
       @articles = Article.all
   end
   
   def new
       @article = Article.new
   end
   
   def create
       #render plain: params[:article].inspect
       @article = Article.new(article_params)
       
        if @article.save
            flash[:success] = "Article successfully saved"
            redirect_to article_path(@article)
        else
            render 'new'
        end
   end
   
   def update
       
        if @article.update(article_params)
            flash[:success] = "Article successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end
    
    def show
    end

    def destroy

        @article.destroy
        
        flash[:danger] = "Article was successfully deleted"
        
        redirect_to articles_path
        
    end
    
    def edit
    end
    
   private 
   
        def article_params
            params.require(:article).permit(:title,:description)
        end
        
        def set_param
            @article = Article.find(params[:id])
        end
        
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@ninety_ten_booking %>

<div class='row'>
    <div class='col-xs-12'>    
        <%= form_for(@ninety_ten_booking, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of ninety_ten_booking", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of ninety_ten_booking" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-lg'%>
            </div>
        </div>        
    </div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to aricles listing", ninety_ten_bookings_path %> ]
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<% @articles.each do |article| %>
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>       
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100)  %>
            </div>
            <div class="article-actions">
                <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete this article", article_path(article), method: :delete,
                                                                                    data: {confirm: "Are you sure you want to delete this article?"}, 
                                                                                    class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
<% end %>
    
<%= link_to "Create new article", new_article_path %>
</table>

app/views/articles/new.html.erb
<h1 align="center">Create a new Booking</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this article", article_path(@article), method: :delete,
                                                                            data: {confirm: "Are you sure you want to delete this article?"}, 
                                                                            class: "btn btn-xs btn-danger" %>
        <%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-success" %>                                                                            
    </div>
</div>


    